### ISSUE TITLE
Return Raw mode for Extracts

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPy#121]
Remove technique requires raw match, thus requiring a copy of any Extract that might be removed.  Need a way to run the Wrangle in raw mode either thru XL UI or as a special version of Copy (that doesn't actually copy) that points to the same reference data as the standard Extract.

**Comment by ebhills** [comment]
Short-term soln: @thomasstvr to develop a Recipe that clones / modifies a Standard Extract to create the Raw Extract.  @ChrisWRWX will assist

**Comment by ChrisWRWX** [comment]
run as recipe to update a sister (Raw) wrgl. Available in Misc Recipes
