### ISSUE TITLE
create.column can create columns which already exist

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPy#124]
Need some sort of validation that checks to see if the column which is being created does not already exist.

![image](https://user-images.githubusercontent.com/65630492/214675225-9bf45be3-229e-47c0-9d51-d8d25164298b.png)

Size column already exists in above example, df then has 2 columns named Size.

**Comment by cerdamario13** [comment]
Resolved, will be in devs branch and then in the next version update
