### ISSUE TITLE
Extract - Remove Duplicates when matching Variants

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPy#130]
Consider this regex: (\d+(?:,)?\d+) (?:strokes per minute|spm)  If I feed the Extract 2 columns where 1 contains spm and the other strokes per minute, the results include the return twice (e.g. Stroke Speed: 3,000, Stroke Speed: 3,000).   Chrius mentikoned that it's probably because the wrgl checks for dupes too early in the processing.

**Comment by ChrisWRWX** [comment]
Fixed. Server side code so doesn't require a package update.
