### ISSUE TITLE
Wrangling Attribute 1, 2 etc Requirements

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPy#137]
- Create a Value+UoM dictionary containing {"Value": 32, "UoM": "mm"} using merge.to_dict
- For Values that don't have UoM, this should return Null / Naan
- Coalesce V+UoM and plain Value Field so that the value for the final object is reflects whether the Value has a UoM or not (or if it's better to have UoM be empty that could work too but seems sub-optimal) >>  {"Value": 32, "UoM": "mm"} or "Value": "ICM 0610 IC908"
- Create object containing all Attributes from the A.x Names and Coalesced Values like {"Blade Height":  {"Value": 32, "UoM": "mm"}, "ANSI Code": "ICM 0610 IC908"} using merge.key_value_pairs
- Do all of this with *s so we can succinctly manage lots of column sets
- Chris mentioned incorporating .to_json into these merge wrangles so that you don't have to add that to the recipe

**Comment by ChrisWRWX** [comment]
Closing this. Looks like many are now addressed - can reopen new issues for any specific items that remain.
