### ISSUE TITLE
Only Getting One Dictionary Value Where there are multiple

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPy#158]
My Power Tools Atributes correctly extracts 3 different values: Cutting Capacity: Mild Steel 0.1875, Cutting Capacity: Soft Wood 2-11/16", Cutting Capacity: Aluminum 0.375. But when I split.dictionary it only gives back 1.  I thought it was supposed to return a list as the value in that case...need it to.

**Comment by cerdamario13** [comment]
Added to v1.2.1
