### ISSUE TITLE
Column Name Error on Chat Extract Wrangle

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPy#160]
It looks like the Wrangle is submitting the input Header to CHAT because the result Header says "No text was provided for summarization." regardless of how many rows are sent.

**Comment by ChrisWRWX** [comment]
It's an edge case because the batch size is smaller than the threshold that triggers it to include the header, so regardless of how many batches it never adds it. I slightly increased the batch size.

Going to add a new issue regarding general heading logic.
