### ISSUE TITLE
Allow split.dictionary to deal with null values

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPy#167]
If split.dictionary is ran on a column containing null values it breaks. Possibly sub in an empty dictionary where null values are located.

**Comment by thomasstvr** [comment]
Same things happens for convert.from_json

**Comment by cerdamario13** [comment]
in [branch v1.2.2](https://github.com/wrangleworks/WranglesPy/tree/v1.2.2)
