### ISSUE TITLE
Pandas Major Version Update

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#198]
Compare performance for pandas 2.X and 1.X, in particular regarding methods for accessing data in columns. Look out for any warning with the new version.

https://pandas.pydata.org/pandas-docs/version/2.0/whatsnew/v2.0.0.html#copy-on-write-improvements

- List comprehension
- Apply
- iter methods e.g. iterrows

**Comment by cerdamario13** [comment]
dataFrame rows: `1_000_000`
columns to upper: `1`
Sample Size: `10` -> The operation was repeated 10 times and average taken

I did not see any warnings. Check scenario as described on issue #168 

v2 | Average Time (ms)
-- | --
List comprehension | 0.175
apply | 0.431
iterrows | 138.146
for loop | 0.242


v1.X | Average Time (ms)
-- | --
List comprehension | 0.173
apply | 0.435
iterrows | Did not attempt
for loop | 0.245

**Comment by cerdamario13** [comment]
Did not see any warnings when replicating #168
