### ISSUE TITLE
Sorted List Output from Extracts

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#209]
Months ago Thomas and I came up w a technique for getting more versus less specific results out of Extracts. You simply put the most specific ones higher in the list.  With this, you could then use first element to relaibily get the correct output. The sorting according to the orde of the regex no longer appears to work. Did something change? What's really wied is that I changed the order of the regex and the order of the ouput stayed the same!

**Comment by ChrisWRWX** [comment]
Thomas spotted this yesterday, he's investigating. It seems like a bug that was introduced relatively recently.

**Comment by ChrisWRWX** [comment]
Update: we've done some digging into this. There are a few overlapping behaviours and changes, which is making it difficult to totally pin down. There was a change that uses set and seems to be the predominant cause, but there seems to be an additional subtle change to the behaviour from a minor update of the python version used in the container.

We fixed the set issue to an alternative that preserves the order. It is fixed now for regex. I don't believe this has ever worked for the non-regex records so I'm going to close this issue and add a new issue for an enhancement on the extract repo to investigate a solution to allow that to work too. As is stands those come out in the order encountered within the input, not determined by the training data order.

**Comment by ebhills** [comment]
Sounds good.  I have an enhancemnt idea that I'd like to incorporate into that next enhancement. Relying on the sort order of the patterns is probelmatic because if the user sorts the table when editing, the preferred sort may be lost.  So in additon to or instead of the list sort, I'd suggest a subset sort (column?).  What I mena is that if there are related patterns (suction & discharge, discharge) that the use case assign a relative sort to just those too. For example specifying -- sd01, sd02 on the 2 rows.  That way user can sort the list as needed without breaking the preferred sort order.
