### ISSUE TITLE
Prefix / Suffix Option: do not add if empty

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#211]
I want to use suffix to add a UoM but I dont want it to do so when the input is empty.  Let's add a parameter like **omit_if_empty** defaulted to true.

**Comment by ChrisWRWX** [comment]
Planning to address this with #218 (allowing a where condition for wrangles) rather than coding a specific solution for this.

Prior to that being deployed you could add the suffix and then replace anything matching exactly the suffix back to nothing.
