### ISSUE TITLE
Enable custom functions for model-based recipes

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#269]
Allow using custom functions for recipes referenced by model ID.

**Comment by thomasstvr** [comment]
It seems the splitting of functions (_read_recipe, _load_functions, _load_functions) has somehow broken things to produced "Access Denied to model" errors. Leaving note here for future reference.

**Comment by ChrisWRWX** [comment]
Let's take a look at this together and figure out how to restructure the code.
