### ISSUE TITLE
Improve extract.ai error handling

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#306]
When exceeding an openai model's maximum context length the error reads:

AttributeError: 'str' object has no attribute 'values'

**Comment by ChrisWRWX** [comment]
This is probably not as relevant now with the extended context length, so make this issue more general.

**Comment by ChrisWRWX** [comment]
Appropriate errors for:
- [ ] Exceeded context length
- [ ] Invalid API key
- [ ] Invalid input definition
- [ ] Other unanticipated errors?
