### ISSUE TITLE
Memory Column Output from Tokenize is Empty

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#341]
I ran a simple tokenize:
  - split.tokenize:
      input: Material Name # DistrE Article
      output: DistrE Article tokens

Using this write, the sheet is created but the column output is empty.
  - split.tokenize:
      input: Material Name # DistrE Article
      output: DistrE Article tokens

It works as expected with dataframe.

**Comment by ChrisWRWX** [comment]
This is just that objects are not yet converted to JSON automatically for Excel using this mechanism.

I've included this on the main issue for the excel write config issue.
