### ISSUE TITLE
Where/convert.to_json Does Not Work With Embeddings

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#342]
When using a where statement on a dataframe that contains embeddings, a TypeError (Object of type float32 is not JSON serializable) occurs. This occurs when converting the column to a json array using (convert.to_json) which is called from main.sql.

 From convert.to_json:
 ```python
    # Loop through and apply for all columns
    for input_columns, output_column in zip(input, output):
        df[output_column] = [
            _json.dumps(row, ensure_ascii=ensure_ascii, **kwargs) 
            for row in df[input_columns].values.tolist()
            ]
```

**Comment by ChrisWRWX** [comment]
This fix adds a handler for numpy floats/ints, arrays and other misc data types such as datetimes that have a __str__() method.

It will work for where, but will have the potential side effect of not preserving the numpy objects as is, but instead converting to python equivalents, depending on how exactly it's used. Intending to look at a broader approach to that.
