### ISSUE TITLE
extract.ai - add parameters to specify header level system prompts and slot to list examples

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#346]
I love this capability!!

1. Can we add a parameter that accepts an overall prompt? Such as, "leave fields blank rather than outputting N/A" etc.
2. For each output, can we add a param for examples? Adding them at the end makes for poor readbility (I know you can wrap but that requires knowledge and adds effort)
> output:
>  Material:
>       type: string
>       description: what the part is made of.
>       **examples: PTFE, Steel, 304SS, CS etc.**

**Comment by ebhills** [comment]
Great!

**Comment by ChrisWRWX** [comment]
Added those two to the schema. There's a whole bunch of options, perhaps we can dynamically reference the JSON schema schema...

@thomasstvr can you add this to the wrangles.io docs? You can see the schema def I added for the function here:
https://github.com/wrangleworks/WranglesPY/blob/main/wrangles/recipe_wrangles/extract.py#L65
