### ISSUE TITLE
Extra Column Extract (without custom code)

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#363]
In order to leverage our ability to add additional columns to Extracts, we need to allow the PY version of the extract to return these values.  We could just make the output a list object like rename:
```
custom.extract:
   input: my colm
   output:
      Output:  my output # this is the Output (Optional)
      my extra col 1:  my second output

# when you want all
   output: {*}

# when you just want the main output
   output: {}
```
The above notation is not meant to be literal, just including it to highlight we should make all 3 scenarios easy to express.

As I write this, it strikes me that it might be better to just create another extract wrgl such as custom.exact_multiple. It would make it cleaner to support the first two, and not create any issues with existing extracts..

**Comment by ChrisWRWX** [comment]
Going to close this. This should be convered by extract + lookup without adding a lot of complexity to extract.
