### ISSUE TITLE
split_dictionary: capture / handle Bad JSON Error?

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#365]
The following row (from the SRS dedupe project) is evidently bad JSON:
"{""Row_Num"": ""86076"", ""Item"": ""NSBELHARR00003"", ""Vendor PN"": """", ""Supplier Name"": ""MERLIN INDUSTRIES INC"", ""Description"": ""CUSTOM MERLIN LINER"", ""Extended Description"": ""18 x 36 RECT.
\n40 INCH - 6 FEET DEEP
\nSPORT BOTTOM w/COVE ONE SIDE
\nWALL SEAM C.S.E.
\nSTD. BEAD
\nBLUE LAPIS 27 MIL PRINT
\n
\nTAG: AQUAFUN/FORLZZI PK
\n AQUAFUN POOLS INC ZZHBG 717-896-7777"", ""size"": ""CIGLMERLIN""}"

(Note: I pasted this here as plain text. If the problem is a weird hiddden char it might have been left out)
This causes an error when running split_dictioanry in the Recipe, but interestingly when you run the stock Expand JSON on a full column  it processes all of the other rows (that's how Chris found the one that was the problem).

Let's figure out how the Recipe can handle the row error and keep going to the remaining rows.  

PS: I think I saw something similar in PRA when trying to use the AI extract to parse some bad JSON that had been retrieved. Point is - let's see if we can come up with an approach that takes care of this everywhere.

**Comment by ChrisWRWX** [comment]
Presuming this was interpreted using from_json. This can now be addressed by adding a default to the recipe in the case of failure or empty values.
