### ISSUE TITLE
Remove words: some letters in words get cutoff

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPY#376]
There is still an issue with remove words where a certain words are cutoff.
This seems to happen when having more than one `to_remove:`
also when mixing strings and arrays in to_remove. eg:

```yaml
to_remove:
  - list
  - string_with_comma
```
Using tokenize to remove gives the same output

**Comment by ebhills** [comment]
Have you asked Copilot to look at it and see what it says?  This needs to get fixed asap.

**Comment by cerdamario13** [comment]
I got some time, let me give it a look
