### ISSUE TITLE
Recipes: Sort order isn't preserved for recipes loaded as objects

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#485]
If you don't specify columns in your write, the order of the columns is opposite of the order they are created. The order should align by default.
```
      read:
        - test:
            rows: 1
            values:
              Status: File Submitted
              Results File: Results - ${date}.xlsx
              Match Columns: ${Similarity Columns}
```
produces
Match Columns |	Results File	| Status
---|---|---|
["Product Group","Supplier","Supplier Part No.","Description","Size","Color"] |	Results - 2024-04-28.xlsx |	File Submitted

**Comment by ChrisWRWX** [comment]
Are you doing something after this? I'm not able to reproduce these results. The order of the dataframe created matches the order specified in values as you'd expect.

**Comment by ebhills** [comment]
it's the Semantic Match Async Recipe.  4c66.  So yes, there is stuff after:
```
  - recipe:
      read:
        - test:
            rows: 1
            values:
              Status: File Submitted
              Results File: Results - ${date}.xlsx
              Match Columns: ${Similarity Columns}
              Ref DB: ${Reference File}
              Subject: ${Email Subject}
      write:
        - excel.sheet:
            action: append
            columns:
              - Status
              - Subject
              - Results File
              - Ref DB
              - Match Columns

run:
  on_success:
    - custom.http:
        url: https://api.github.com/repos/wrangleworks/action-demo/actions/workflows/matching.yml/dispatches
        method: POST
        headers:
...
```
Note that I added columns to deal with it.  If you take the columns out you should see it.
