### ISSUE TITLE
select.element Does Not Allow Index Slicing as Intended

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#499]
As I understand it, select.element is meant to allow slicing like:

```
  - select.element:
      input: links[0:3]
      output: links
```

This does not work because the element is taken in as a string ('0:3' in this example), then the wrangles attempts to convert that string to an integer which causes the silent failure.

```
            for element in elements:
                try:
                    if isinstance(row, list):
                        row = row[int(element)]
```

**Comment by ChrisWRWX** [comment]
Are you looking at an old version of this? It splits it and creates a slice object.

```py
for element in elements:
  try:
    if isinstance(row, (list, str)):
      if ":" in element:
        row = row[slice(*map(_int_or_none, element.split(":")))]
```

Going to close this as I'm fairly sure you're just referencing an old version and it'll be solved by updating, but please reopen if I'm mistaken.
