### ISSUE TITLE
Explode Silent Failure

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#510]
Explode fails silently when exploding on a column made up of incomplete list. Ie a list that does not have closing brackets.

**Comment by ChrisWRWX** [comment]
An incomplete list without a closing bracket can't be a genuine list, presumably a string that was intended to be a JSON array?

Explode treats scalar values effectively as a list of one element and after exploding you get the row back unchanged. I don't think explode in this case can be expected to anticipate that you meant to have a list.

Note: we don't currently have any code that would catch a JSON string that was supposed to be a list, so a complete JSON list wouldn't work either. It would need convert.from_json first which would error on the invalid syntax.
