### ISSUE TITLE
Extract.ai Examples as an Array

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#512]
When passing through examples to extract.ai, if the examples are not passed as an array the code breaks.

Could we add logic to the code that adds them to a list like we do the input/outputs of most wrangles? Or maybe something in the schema that adds a squiggly line to let users know?

**Comment by ChrisWRWX** [comment]
examples is an array in the JSON schema definition, so passing a non-array isn't a valid schema definition.

It does already indicate this is an error, are you seeing an example where it doesn't?

![image](https://github.com/wrangleworks/WranglesPY/assets/58178530/b61b2274-8935-4129-931d-2e4c7ba82bcb)

Converting it to an array in the background if it isn't already seems like a sensible precaution.

**Comment by thomasstvr** [comment]
Maybe it's a WranglesPY version thing since I've been using the dev version with batching?

![image](https://github.com/wrangleworks/WranglesPY/assets/65630492/35aa44b9-bc8f-4dec-91cf-910d04210648)
