### ISSUE TITLE
Custom Functions Within Accordion

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#530]
It seems that a silent failure occurs when trying to use a custom function (within an accordion) that is not listed in the functions list.

While running the recipe, it seems that the accordion closes at the (unlisted) custom function and keeps running without failure.

**Comment by ChrisWRWX** [comment]
Closing this. I believe this was just due to the on_error of batch catching the errors. Otherwise, the error would have been raised as normal.
