### ISSUE TITLE
Classify wrangle test keeps failing

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPY#548]
Classify wrangle: `a62c7480-500e-480c` randomly fails in Github actions. This is most likely due to retraining.
The error misclassifies Cheese as meat and not dairy

Here is the model being retrained in tests
![image](https://github.com/user-attachments/assets/cc5c1716-03b9-4fb1-ac9e-9bb13d407c78)

**Comment by ChrisWRWX** [comment]
Hopefully resolved with updates and classify v2
