### ISSUE TITLE
filter Wrangle data type/format mismatch

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#63]
When using filter wrangles, I have seen that data can be in the format:
-  '8.01543E+11'
- 801542476847

This causes filter functions to not find appropriate values.

Look into getting both of the comparing columns (values) into the same format/type.
Look into using pandas import csv functions. For excel, the current code already deals with this (test to make sure).

**Comment by cerdamario13** [comment]
One way to make sure this does not happen is to make sure the csv/excel column is set to number

**Comment by ChrisWRWX** [comment]
I don't believe this should happen with a csv unless the data is already affected? If so, it's too late once it's made it into the csv as '1.234E+56'. However, this could make a nice wrangle to convert to/from scientific notation - with the limitation that you may not be able to recover the full original value if it's been rounded as in your example.

This is a common Excel issue. The parameter dtype allows specifying the data types, as a dictionary by column if needed so it could be enforced within the recipe. We're defaulting it to 'object', which preserves the data types stored in Excel - so this could also potentially be addressed by specifying an appropriate data type within the source Excel file.

Can you generate a brief example file/recipe where this happens?

**Comment by cerdamario13** [comment]
The issue occurs if, in the Excel file to CSV, the type is left as General as opposed to Number.
