### ISSUE TITLE
Oracle Connector without Oracle Client libraries

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#82]
Update the Oracle connector to work without having to use Oracle Client libraries. Look into Oracle thick and thin.
More info can be found [here](https://oracle.github.io/python-oracledb/) regarding thin/thick mode.

**Comment by cerdamario13** [comment]
More info
- [Table](https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_a.html#featuresummary) of differences of `Thin` and `Thick` mode.

**Comment by ChrisWRWX** [comment]
Closing this. Will return to it as and when an Oracle connector becomes a priority.
